[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 10_000
via_ir = false
gas_limit = 9_000_000_000
fs_permissions = [{ access = "read", path = "./" }]

[fuzz]
runs = 1000

[rpc_endpoints]
mainnet = "${ETH_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}", chain = 1 }
sepolia = { key = "${ETHERSCAN_API_KEY}", chain = 11155111 }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md
